server:
  port: 9090

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_oauth2?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: nhanbn98

